### ISSUE TITLE
Fix broken readme link

### ISSUE THREAD

**Issue by guywarner** [guywarner/laravel-google-chat-alerts#2]

**Comment by lukasmedia** [comment]
Hi,
I cannot open a new issue/bug report. But here's a new bug.

I did the installation (laravel 8) and a test message. Nothing happens. In the log i find:

The script tried to call a method on an incomplete object. Please ensure that the class definition "GuyWarner\GoogleChatAlerts\Jobs\SendToGoogleChatChannelJob" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition {"exception":"[object] (Error(code: 0): The script tried to call a method on an incomplete object. Please ensure that the class definition \"GuyWarner\\GoogleChatAlerts\\Jobs\\SendToGoogleChatChannelJob\" of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide an autoloader to load the class definition at /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php:117)

**Comment by guywarner** [comment]
Thanks for letting me know the issue isn't working.

This was built for Laravel 9, I'll add it to readme.
